# Generated by Selenium IDE
import pytest
import time
import json
from conftest import get_driver, get_url # 1) Replace from selenium import webdriver with this
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWelcome():
  def setup_method(self, method):
    self.driver = get_driver() # 2) use get_driver here
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_welcome(self):
    # 3) Replace url with get_url()
    self.driver.get(get_url())
    # 4) Before find_element ... click add element_to_be_clickable wait
    WebDriverWait(self.driver, 5).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "#js-link-box-en > strong")))
    self.driver.find_element(By.CSS_SELECTOR, "#js-link-box-en > strong").click()
    # 5) Before access add presence_of_element_located wait
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.ID, "Welcome_to_Wikipedia")))
    assert self.driver.find_element(By.ID, "Welcome_to_Wikipedia").text == "Welcome to Wikipedia"
  
