name: Selenium
on: push
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Installing python packages
        working-directory: tests
        run: pip install -r requirements.txt
      - name: Run tests
        working-directory: tests
        run: pytest --url `cat ../url.txt` --junit-xml=test-results.xml
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: tests/test-results.xml
          summary: true
          fail-on-empty: true
          title: Test results
        